### ISSUE TITLE
Drop ImageMetadata dependency

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageMorphology.jl#1]
Could we remove ImageMetadata.jl from the dependency list of this module? The tests indicate that it is only there to wrap the actual operations for general images. This could be done at the Images.jl level instead: https://codecov.io/gh/JuliaImages/ImageMorphology.jl/src/master/src/morphological_operations.jl

Can I proceed with the idea?

**Comment by timholy** [comment]
Yeah, move those back to Images.jl and drop them from ImageMorphology.

**Comment by juliohm** [comment]
Will do, thanks.
