### ISSUE TITLE
Add ability to erode/dilate using structuring elements

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/ImageMorphology.jl#11]
In Matlab you can provide a structuring element to erode/dilate along: https://www.mathworks.com/help/images/ref/strel.html. This would be useful to have here too.

**Comment by twinGu** [comment]
Don't know if it belongs here, but I wrote a quick generalized implementation of the `_extremefilt! ` function, which can take a `dist` parameter, where `dist=1` equals a 3x3 structuring element in 2D and `dist=2` equals a 5x5 structuring element in 2D etc. I didn't write tests for `dist>1` yet, but the existing tests for `dist=1` all pass. I don't know if it helps, but if anyone is interested, here is my fork:

https://github.com/twinGu/ImageMorphology.jl

If there is interest for a pull request, I can also write up some tests and would be happy about some advice for improvements I could work in.

**Comment by timholy** [comment]
This seems as good a place as any to discuss structuring elements. We unfortunately seem to have a few conventions being used:
- `dims = 1:n`. In most places this implies "diamond" connectivity, but for `erode`/`dilate` it's equivalent to `CartesianIndices` (box)
- `window = (3, 3, 3, ...)`. This is basically iterating over the CartesianIndices of a box around the center point.
- `connectivity::AbstractArray{Bool}`. Currently we don't insist that it be `centered`, and we interpret the center as the origin. When all values of `connectivity` are true, this is the same as `window = size(connectivity)`
- some languages support a `dist` integer or real number, typically a Manhattan or Euclidean distance 

It would be nice to standardize these, or at least make them all mean the same thing throughout JuliaImages. Thoughts on how to unify them? `connectivity` is the most general of all of these but iterating over it is slow unless we convert to a Static variant; this has a runtime dispatch penalty but it should be pretty negligible for all but tiny images.

**Comment by johnnychen94** [comment]
This is supported by #65 and #80. The 0.4 release might be within a month if everything works smoothly.
