### ISSUE TITLE
find_root_unsafe! does not support Int32

### ISSUE THREAD

**Issue by kongdd** [JuliaImages/ImageMorphology.jl#112]
```julia
nested task error: MethodError: no method matching find_root_unsafe!(::ImageMorphology.DisjointMinSets{Int32}, ::Int32)
```

In Line 141, `m::Int` should be `m:Integer`.
<https://github.com/JuliaImages/ImageMorphology.jl/blob/e7c206c1a6a7b2da973e3474ed69e2c8052c19f7/src/connected.jl#L141>

**Comment by johnnychen94** [comment]
would you mind submit a small PR for this? Thanks in advance
