### ISSUE TITLE
Unable to use v0.4.x with Images.jl

### ISSUE THREAD

**Issue by cpaniaguam** [JuliaImages/ImageMorphology.jl#114]
I'd like to use dilate/erode with structuring elements in version 0.4.x with some basic file IO operations in Images.jl. However, there is some dependency that pins ImageMorphology to version 0.3.2 (no support for se :/).

```
(myenv) pkg> status --outdated
Status `~/Documents/myenv/Project.toml`
⌅ [787d08f9] ImageMorphology v0.3.2 (<v0.4.2): ImageSegmentation, Images
```
Could someone please help me figure out how to use ImageMorphology v0.4.x with file IO? I tried adding minimal dependencies for file IO but then I get errors due to ImageMagick when saving using `save` during testing.

```
(myenv) pkg> st
Status `~/Documents/myenv/Project.toml`
  [5789e2e9] FileIO v1.15.0
  [82e4d734] ImageIO v0.6.6
  [6218d12a] ImageMagick v1.2.2
  [787d08f9] ImageMorphology v0.4.2
```

Thanks!

**Comment by johnnychen94** [comment]
> I tried adding minimal dependencies for file IO but then I get errors due to ImageMagick when saving using save during testing.

The dependency looks good to me. Would you mind posting the error message and how you get that? A minimal working example.

**Comment by cpaniaguam** [comment]
I just create a new environment in the normal way:
```
(@v1.8) pkg> activate .
  Activating new project at `~/Documents/mypkg`
(mypkg) pkg> add ImageMorphology Images
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/Documents/mypkg/Project.toml`
⌅ [787d08f9] + ImageMorphology v0.3.2
  [916415d5] + Images v0.25.2
    Updating `~/Documents/mypkg/Manifest.toml`
...
⌃ [6218d12a] + ImageMagick v1.2.1
  [bc367c6b] + ImageMetadata v0.9.8
⌅ [787d08f9] + ImageMorphology v0.3.2
...
        Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated -m`
(mypkg) pkg> st --outdated -m
Status `~/Documents/mypkg/Manifest.toml`
⌃ [6218d12a] ImageMagick v1.2.1 (<v1.2.2)
⌅ [787d08f9] ImageMorphology v0.3.2 (<v0.4.2): ImageSegmentation, Images
(mypkg) pkg> st
Status `~/Documents/mypkg/Project.toml`
⌅ [787d08f9] ImageMorphology v0.3.2
  [916415d5] Images v0.25.2
Info Packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`

(mypkg) pkg> 
```
The latest `Images` was installed along with v0.3.2 of `ImageMorphology`. I was hoping for v0.4.x.

**Comment by johnnychen94** [comment]
There's no plan to ship ImageMorphology v0.4 with Images (https://github.com/JuliaImages/Images.jl/pull/1011) because this is a transient-breaking version.

> then I get errors due to ImageMagick when saving using save during testing.

I mean, how did you get the error? Is that due to ImageMorphology v0.4, or is it something else?

**Comment by cpaniaguam** [comment]
Thanks for the reference to the issue! 

ImageMorphology v0.4 is working as it should. For now I'll just remove the call to `save` from the tests and anticipate v0.5!
