### ISSUE TITLE
How to Apply Weighted Distance Transform

### ISSUE THREAD

**Issue by SebKrantz** [JuliaImages/ImageMorphology.jl#129]
Hi, sorry if I am being ignorant here, but I am not managing to compute a weighted distance transform. The documentation says the weights should be a tuble. I wonder why? Why cannot the image and weights just be passed as numeric matrix? E.g. 

```jl
X = rand(10,10)  # input image
W = rand(10,10)  # weights

distance_transform(feature_transform(X, W), W)
```
To provide some context, I am trying to translate a line of matlab code

```m
graydist(W, X, "quasi-euclidean")
```
The function comes from the image processing library: https://www.mathworks.com/help/images/ref/graydist.html#bs0wqxd-1-CR

Thanks!

**Comment by timholy** [comment]
From the docs:

> Optionally specify the weight w assigned to each coordinate. For example, if I corresponds to an image where voxels are anisotropic, w could be the voxel spacing along each coordinate axis. The default value of nothing is equivalent to w=(1,1,...).

The weights set the coefficient of the metric used to compute the distance between pixels/voxels.

**Comment by SebKrantz** [comment]
Thanks, I see now, the function cannot be used to compute a gray-weighted distance transform of an image with quasi-euclidian metric, although it gives the same result when all weights are equal to 1 (i.e. no weights are used). 

Just in case this is of interest for the package, I found an octave implementation at https://github.com/shsajjadi/OctaveUnimplemented/blob/master/graydist.cc, and made an AI assisted Julia translation of it which appears to give the intended results, at least in my simple use cases

```jl
# This was generated by Claude 2 based on the Octave C++ implementation at:
# https://github.com/shsajjadi/OctaveUnimplemented/blob/master/graydist.cc 
"""
    graydist(I, seeds, metric="quasi-euclidean")

Compute gray weighted distance transform of image I using quasi-euclidean metric.
seeds is a boolean mask indicating seed points. 
"""
function graydist(I::AbstractMatrix, seeds::AbstractMatrix, metric="quasi-euclidean")

    # Check inputs
    size(I) == size(seeds) || error("I and seeds must have same size")

    metrics = ["quasi-euclidean"]
    metric ∈ metrics || error("Invalid metric $metric")

    T = similar(I, Float32) 
    fill!(T, Inf)
    idx = similar(seeds, Int)
    
    shifts = ((-1,0), (1,0), (0,-1), (0,1), (-1,-1), (-1,1), (1,-1), (1,1))
    
    fringe = CartesianIndex{2}[]
    for i in CartesianIndices(seeds)
        if seeds[i]
            push!(fringe, i)
            T[i] = 0
            idx[i] = 0
        end 
    end
    
    while !isempty(fringe)
        u = pop!(fringe)
        
        fu = I[u]
        for shift in shifts
            v = u + CartesianIndex(shift)
            if checkbounds(Bool, I, v) && T[v] > T[u] + cost(fu, I[v], u, v)
                T[v] = T[u] + cost(fu, I[v], u, v)
                idx[v] = idx[u]
                push!(fringe, v)
            end
        end
    end
    
    return T #, idx
end

function cost(fu, fv, u, v)
    root2 = sqrt(2)
    h = 0.5
    x1, y1 = Tuple(u)
    x2, y2 = Tuple(v)
    
    if abs(x1 - x2) > abs(y1 - y2)
        return h*(fu + fv) + (root2 - 1)*abs(y1 - y2)
    else
        return (root2 - 1)*abs(x1 - x2) + h*(fu + fv) 
    end
end
```

**Comment by timholy** [comment]
Thanks! It's of interest, but since the original is GPL we can't use this at all. Would you do me the favor of editing the above to delete the text, just to prevent someone else from coming along and copying it?
