### ISSUE TITLE
Export in-place functions like closing!

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/ImageMorphology.jl#19]
Is there any specific reason that we don't export the in-place functions like closing! and company?

**Comment by johnnychen94** [comment]
No not at all as far as I've understood. I once noticed this but forgot to export them.

cc: @juliohm

**Comment by juliohm** [comment]
Thanks @tlnagy for catching this. Please feel free to submit a PR. :+1:

**Comment by johnnychen94** [comment]
Will be exported in 0.4.0
