### ISSUE TITLE
move `clearborder` from Images.jl to ImageMorphology.jl

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageMorphology.jl#27]
https://github.com/JuliaImages/Images.jl/blob/988cd8764249c2c9c7b3b8ca3e163f39f2f258aa/src/algorithms.jl#L862-L910

**Comment by mgautam98** [comment]
@johnnychen94 Doing that will add a dependency TiledIteration: EdgeIterator, would that be okay?

**Comment by johnnychen94** [comment]
Yes, moving dependency from Images.jl to subpackages can actually be a benefit. If you check [`Images.jl/Project.toml`](https://github.com/JuliaImages/Images.jl/blob/master/Project.toml), you'll easily get lost in those versions and have no idea which packages are unnecessary.

**Comment by johnnychen94** [comment]
closed by #29
