### ISSUE TITLE
[features] most wanted features for contributing? 

### ISSUE THREAD

**Issue by ThomasRetornaz** [JuliaImages/ImageMorphology.jl#57]
Hi i m experimented morphologycal guy (phd in this domain) but im quiet new in julia comming from c++ community 
So what features will be the most valuable if i could contribute
* speedup erode/dilate with simd?
* implement seg tools eg whatersed
* generalize labelizations algoritms
* more generally add benchmarks to find
 bootleneck
*... 
Let me know
Regards

**Comment by johnnychen94** [comment]
Thanks for the interest. I suggest you contribute to things that you're interested in most and happen to improve the community.

> speedup erode/dilate with simd?

This would be much helpful! As for the benchmark, setting up a benchmark cases folder could be the first step, we use PkgBenchmark + BenchmarkCI, you can take a look at [ImageContrastAdjustment.jl](https://github.com/JuliaImages/ImageContrastAdjustment.jl/tree/master/benchmark) as an example. We'll also have [a comprehensive collection of benchmark cases](https://github.com/JuliaImages/image_benchmarks) against other frameworks in the future.

> implement seg tools eg whatersed

Most of segmentation methods are included in ImageSegmentation.jl, including watershed.

**Comment by juliohm** [comment]
Adding to what Johnny said, I suggest to try to contribute in an area where
your expertise makes a difference. Performance improvements are great but
any experienced Julia programmer can sit down and try to boost existing
codes. If you have expertise in mathematical morphology you can probably
add new algorithms that only a few people could contribute.

Em dom., 20 de mar. de 2022 08:57, Johnny Chen ***@***.***>
escreveu:

**Comment by ThomasRetornaz** [comment]
Thanks for your reply
So may a good start for me is to populate a benchmark suite and then add some geodesic operators (eg geodesic erode /dilate, under/overbuild, hmin, hmax, dynamicopening and levellings) so the library cover most of geodesic operators wich seems missing in the repo
Note:i found hmin in ImageSegmentation.jl but it seems the naive implementation 
I will learn julia along the path so be patient
We could discuss further what is the most suitable after
King regards

**Comment by johnnychen94** [comment]
I'm closing this issue as there are no specific targets to do here. Feel free to open new issues/PRs when you have concrete ideas in mind.
